version: "3"
services:
  web:
    build: .
    env_file: .env
    environment:
         - NODE_ENV=production
         - REDIS_URL=redis://redis_db:6379
    ports:
     - "${PORT}:${PORT}"
    depends_on:
      - redis_db
  redis_db:
    image: "redis:alpine"
    restart: always